#!/bin/bash

# Install dotfiles
if [ ! -d $HOME/.dotfiles ]; then
  git clone https://github.com/mikemackintosh/dotfiles $HOME/.dotfiles
else
  cd $HOME/.dotfiles
  git pull --rebase
fi

# Create private dir
if [ -d "${HOME}/.private/" ]; then
  mkdir $HOME/.private
  touch $HOME/.private/nil
fi

# Backup
if [ -f $HOME/.bash_profile ]; then
  mv $HOME/.bash_profile $HOME/.bash_profile.orig
fi
if [ -f $HOME/.atom ]; then
  mv $HOME/.atom $HOME/.atom.orig
fi
if [ -f $HOME/.gitconfig ]; then
  mv $HOME/.gitconfig $HOME/.gitconfig.orig
fi
if [ -f $HOME/.vim ]; then
  mv $HOME/.vim $HOME/.vim.orig
fi
if [ -f $HOME/.vimrc ]; then
  mv $HOME/.vimrc $HOME/.vimrc.orig
fi
if [ -f $HOME/.curlrc ]; then
  mv $HOME/curlrc $HOME/.curlrc.org
fi
if [ -f $HOME/.tmux.conf ]; then
  mv $HOME/.tmux.conf $HOME/.tmux.conf.org
fi

# Get readlink
`readlink $HOME/.bash_profile | grep .dotfiles/bash_profile.sh > /dev/null`
BASH=$?
if [ $BASH == 1 ]; then
  ln -s $HOME/.dotfiles/bash_profile.sh $HOME/.bash_profile
  ln -s $HOME/.dotfiles/atom $HOME/.atom
  ln -s $HOME/.dotfiles/gitconfig $HOME/.gitconfig
  ln -s $HOME/.dotfiles/vim $HOME/.vim
  ln -s $HOME/.vim/vimrc $HOME/.vimrc
  ln -s $HOME/.dotfiles/curlrc $HOME/.curlrc
  ln -s $HOME/.dotfiles/atom $HOME/.atom
  ln -s $HOME/.dotfiles/tmux.conf $HOME/.tmux.conf
fi

source ~/.bash_profile

OS=`uname`
if [[ $OS == 'Darwin' ]]; then
  install_osx
fi
